---
title: Microbiome analysis complements fecal occult blood test for improved detection
  of colonic lesions
author: "Nielson T. Baxter, Mack T. Ruffin IV, Mary A.M. Rogers, and Patrick D. Schloss"
csl: nature.csl
output: word_document
bibliography: references.bibtex
---

Colorectal cancer is the second leading cause of death among cancers in the United States [@siegel2014colorectal]. Although individuals diagnosed early have a greater than 90% chance of survival, more than one-third of individuals do not adhere to screening recommendations partly because the standard diagnostics, colonoscopy and sigmoidocsopy, are expensive and invasive [@siegel2014colorectal;@centers2010vital;@hsia2000importance;@jones2010barriers]. Thus, there is a great need to improve the sensitivity of non-invasive tests to detect early stage cancers and adenomas. Numerous studies have demonstrated a causal link between the formation of colonic lesions and the activity of the gut microbiota in tissue culture and animal models [@zackularMbio;@kostic2013fusobacterium;@wu2009human;@arthur2012intestinal]. These findings have been complemented by studies in human populations identifying shifts in the composition of the gut microbiota associated with the progression of colorectal cancer [@wang2012structural;@chen2013decreased;@chen2012human;@shen2010molecular]. These results suggest that the gut microbiota may represent a reservoir of biomarkers that would complement existing non-invasive methods such as the widely used fecal immunochemical test (FIT). Using stool samples from 490 patients we developed a cross-validated random forest classification model that detects colonic lesions using the relative abundance of gut microbiota and the concentration of hemoglobin in stool. The microbiome-based random forest model detected 95.0% of cancers and 61.1% of adenomas while FIT detected 75.0% and 15.7%, respectively. Of the colonic lesions missed by FIT, the model detected 80.0% of cancers and 53.9% of adenomas. To date this is the largest study to characterize alterations in the microbiota associated with colorectal cancer and the first to demonstrate a method by which microbiome analysis improves upon existing screening methods. With a negative predictive value of 99.98%, our model could be used to accurately identify those patients for whom a colonoscopy is unnecessary, potentially reducing healthcare costs and complications due to invasive screening while decreasing the incidence and mortality of colorectal cancer.


